spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/transactionalaccountdb
    username: transactional-account-service
    password: MfdsQwAtfDRK

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true