spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accountdb
    username: account-service
    password: puRNsMeNdREG

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
