spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user-service
    password: a57npk1YqWG3

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
